name: Codespell

on: [push, pull_request]

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install codespell==2.4.1
          pip install tomli

      - name: Run Codespell
        run: |
          codespell || exit
